export {default as bg1} from './fondo1.jpg'
export {default as bg2} from './fondo2.jpg'
export {default as bg3} from './fondo3.jpg'
export {default as bg4} from './fondo4.jpg'
export {default as bg5} from './fondo5.png'
export {default as bg6} from './fondo6.png'